language: python
python:
 - "2.6"
 - "2.7"
 - "3.3"
 - "pypy"
install: 
 - "pip install -e ."
 - "python -c \"import sys, os; if sys.version_info < (2, 7): os.system('pip install unittest2')\""
script: "python runtests.py"
